Registration
joshsoftware/react-e-commerce pull request #4
Opened 2020-09-06 14:27 UTC by Durgesh00

Registration form with test cases

2020-09-07 11:38 UTC, sahilbhatia requested changes
Please check comments and apply to all other components.

2020-09-07 11:38 UTC, sahilbhatia commented on src/components/ButtonWrapper.js
> +};
There is a much simpler way of defining wrapper. To be used untill any specific customizations are required.

```
import { Button } from 'reactstrap';

export default React.memo(Button);
```

2020-09-07 11:38 UTC, sahilbhatia commented on src/components/FormCard.js
> +  const { firstname, lastname, email, password, country, state, city, address } = FormAttributes;
This should be coming through props

2020-09-07 11:38 UTC, sahilbhatia commented on src/components/FormCard.js
> +  };
Should not be defined in this component

2020-09-07 11:38 UTC, sahilbhatia commented on src/components/FormCard.js
> +      </Card>
Move this out to it's own component

2020-09-07 11:38 UTC, sahilbhatia commented on src/components/FormCard.js
> +      </Card>
Move this out to it's own component

2020-09-07 11:39 UTC, sahilbhatia requested changes

2020-09-07 11:39 UTC, sahilbhatia commented on package.json
> +    "eslint": "^6.6.0",
Why did we downgrade the eslint version?

2020-09-08 04:52 UTC, DevKaranPradhan commented on src/components/FormCard.js
> +  };
moved to their own components

2020-09-08 04:53 UTC, DevKaranPradhan commented on src/components/FormCard.js
> +      </Card>
added wrappers of card and cardbody

2020-09-15 14:13 UTC, DevKaranPradhan commented
closed

2020-09-15 14:13 UTC, closed without merging